<script lang="ts">
  import type { PageData } from "./$types";

  // In Svelte 5, props come from $props() instead of `export let`.
  // PageData is generated by svelte-kit and typed from what load() returned.
  let { data }: { data: PageData } = $props();
</script>

<h1 class="page-title">Recent Discussions</h1>

<!-- {#each} is Svelte's loop block. It re-renders for every item in the array. -->
{#each data.summaries as post}
  <p>{post.title}</p>
  <p>{post.content}</p>
  <p>{post.author}</p>
  <p>{post.created}</p>
  <p>{post.updated}</p>
{:else}
  <p class="empty">No posts yet.</p>
{/each}

<style lang="scss">
  .page-title {
    font-size: var(--text-3xl);
    margin-bottom: var(--space-5);
  }

  .empty {
    color: var(--color-text-muted);
  }
</style>
