/// <reference types="node" />
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        // Using process.env directly with a fallback rather than Prisma's env()
        // helper so that commands like `prisma generate` (which never connect)
        // don't fail when DATABASE_URL is absent, e.g. during CI install steps.
        url:
            process.env.DATABASE_URL ??
            "postgresql://placeholder:placeholder@localhost:5432/placeholder",
    },
});
