name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # for now only see if project can be built
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
        env:
          DATABASE_URL: postgresql://dummy_user:dummy_pass@localhost:5432/discussion_forum
      - run: npm run lint
      - run: npm run build
